package net.euler

/**
 * Pentagon numbers
 *
 * Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2.
 * The first ten pentagonal numbers are:
 *
 *     1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 *
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
 * However, their difference, 70 − 22 = 48, is not pentagonal.
 *
 * Find the pair of pentagonal numbers, Pj and Pk,
 * for which their sum and difference are pentagonal
 * and D = |Pk − Pj| is minimised;
 * what is the value of D?
 *
 * User: Alexandros Bantis
 * Date: 6/8/13
 * Time: 11:56 AM
 */
object Problem044 {

  def answer: Long = {
    def isPentagon(x: Long): Boolean = (Math.sqrt(24 * x + 1) + 1) % 6 == 0
    def iter(pentagons: List[Long], i: Int): Long = {
      val k = i * (3 * i - 1) / 2
      val D =
        for {
          j <- pentagons
          if pentagons.contains(k-j) && isPentagon(j+k)
        } yield k-j
      if (!D.isEmpty) D.head
      else {
        iter(k :: pentagons, i+1)
      }
    }
    iter(List(1), 2)
  }
}
