package net.euler

/**
 * Triangular, pentagonal, and hexagonal
 *
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 *        Triangle 	  Tn=n(n+1)/2    1, 3, 6,  10, 15, ...
 *        Pentagonal  Pn=n(3n−1)/2 	 1, 5, 12, 22, 35, ...
 *        Hexagonal   Hn=n(2n−1)     1, 6, 15, 28, 45, ...
 *
 * It can be verified that T285 = P165 = H143 = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 *
 * User: Alexandros Bantis
 * Date: 6/8/13
 * Time: 2:51 PM
 */
object Problem045 {

  def isPentagon(x: Long): Boolean = (Math.sqrt(24 * x + 1) + 1) % 6 == 0
  def isHexagon(x: Long): Boolean = (Math.sqrt(8 * x + 1) + 1) % 4 == 0

  def answer = {
    def iter(i: Long): Long = {
      val T = i * (i+1) / 2
      if (isPentagon(T) && isHexagon(T)) T
      else iter(i+1)
    }
    iter(286L)
  }
}
